s = "Hello"
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.capitalize())
print(s.title())
print(s.isalnum())
print(s.isalpha())
print(s.isdecimal())
print(s.isdigit())
print(s.isidentifier())
print(s.islower())
print(s.isupper())
print(s.istitle())
print(s.isnumeric())
print(s.isprintable())
print(s.isspace())
